apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-component-dtgqaw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-component-dtgqaw
    app.kubernetes.io/part-of: integ-app-pfoq
  name: python-component-dtgqaw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: python-component-dtgqaw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: python-component-dtgqaw
    spec:
      containers:
      - image: quay.io/kasem_org/integration3-puky-tenant/integ-app-pfoq/python-component-dtgqaw@sha256:22db46fa3bb28ed10e7c97b1ed15b81b1c88822a2ca8727f4641eabbb10628a4
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
